project_root: .
seed: 13579 # this does NOT guarantee perfect reproducibility across all TF environments on all hardware

paths:
  # overall filesystem layout expected
  tfrecord: ../data/cases.tfrecord                # serialized tf dataset
  manifest: ../data/cases_manifest.csv            # paired with tf dataset, mostly used for split validation
  train_indices: splits/train_meta_indices.txt    # text file of meta_index values assigned to train
  val_indices: splits/val_meta_indices.txt        # text file of meta_index values assigned to val
  test_indices: splits/test_meta_indices.txt      # text file of meta_index values assigned to test
  artifacts_dir: artifacts                        # where intermediate outputs go
  results_dir: results                            # where final outputs go

data:
  # dataset-level constants shared across scripts
  input_shape: [512, 512, 4]                      # [H, W, C]
  seg_shape: [512, 512, 1]                        # [H, W, 1]
  num_classes: 5
  class_names:
    - epidural
    - intraparenchymal
    - intraventricular
    - subarachnoid
    - subdural

training:
  # shared training params
  epochs: 25                      # max number of passes through training set 
  learning_rate: 1E-4             # magnitude of updates during backprop
  early_stopping_patience: 10     # for keras this means allow x conscutive non-improving epochs before stopping

mlp:
  # MLP model-specific params
  batch_size: 4
  pooled_size: [64, 64]           # [H, W] the tensor is downsampled to
  hidden_units: [1536, 768]       # size of dense layer(s)
  dropout_rate: 0.2               # proportion of dropout layers randomly zeroed
  use_batch_norm: true

cnn:
  # CNN model-specific params
  batch_size: 4
  conv_filters: [16, 32, 64, 128]             # conv filter numbers
  kernel_size: 3                        # convolution window size for conv layers
  dense_units: [512]                    # size of dense layer(s) after global pooling
  dropout_rate: 0.2                     # proportion of dropout layers randomly zeroed
  use_batch_norm: true
  global_pool: avg                      # how feature maps become feature vectors for classification

multiunet:
  # Multitask UNet model-specific params
  batch_size: 2                           # should be smaller than for above; memory-intensive!
  encoder_filters: [8, 16, 32, 64]             # encoder filter numbers
  bottleneck_filters: 128                  # bottleneck filter numbers
  decoder_filters: [64, 32, 16, 8]             # decoder filter numbers
  cls_hidden_units: [512]                 # size of dense layer(s) in classification head
  kernel_size: 3                          # convolution window size for conv layers
  dropout_rate: 0.2                       # proportion of dropout layers randomly zeroed
  use_batch_norm: false
  loss_weight_cls: 0.6                    # multitask loss weight for the classification component  
  loss_weight_seg: 0.4                    # multitask loss weight for the segmentation component

# note: loss weight tuning tba, maybe